### ISSUE TITLE
Code will not run, even after minor fixes

### ISSUE THREAD

**Issue by dchen327** [b-junkoo/Sudoku#1]
Just cloned your repo and attempted to run, getting unpacking errors due to lines like `puzzle, solu = maker()`. After fixing two of these, I'm getting some errors with `local variable 'solu' referenced before assignment`. If needed, I can help clean up some of the code and make a PR!

Good job!

**Comment by b-junkoo** [comment]
Fixed it. It was a problem with the generator script.
